 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/wadgets", type: :request do
  # Wadget. As you add validations to Wadget, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Wadget.create! valid_attributes
      get wadgets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      wadget = Wadget.create! valid_attributes
      get wadget_url(wadget)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_wadget_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      wadget = Wadget.create! valid_attributes
      get edit_wadget_url(wadget)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Wadget" do
        expect {
          post wadgets_url, params: { wadget: valid_attributes }
        }.to change(Wadget, :count).by(1)
      end

      it "redirects to the created wadget" do
        post wadgets_url, params: { wadget: valid_attributes }
        expect(response).to redirect_to(wadget_url(Wadget.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Wadget" do
        expect {
          post wadgets_url, params: { wadget: invalid_attributes }
        }.to change(Wadget, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post wadgets_url, params: { wadget: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested wadget" do
        wadget = Wadget.create! valid_attributes
        patch wadget_url(wadget), params: { wadget: new_attributes }
        wadget.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the wadget" do
        wadget = Wadget.create! valid_attributes
        patch wadget_url(wadget), params: { wadget: new_attributes }
        wadget.reload
        expect(response).to redirect_to(wadget_url(wadget))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        wadget = Wadget.create! valid_attributes
        patch wadget_url(wadget), params: { wadget: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested wadget" do
      wadget = Wadget.create! valid_attributes
      expect {
        delete wadget_url(wadget)
      }.to change(Wadget, :count).by(-1)
    end

    it "redirects to the wadgets list" do
      wadget = Wadget.create! valid_attributes
      delete wadget_url(wadget)
      expect(response).to redirect_to(wadgets_url)
    end
  end
end
